# Generated by Django 4.2.13 on 2024-08-01 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatments', '0002_faq_treatment_benefits_treatment_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='approach',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='treatment',
            name='conditions_treated',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='treatment',
            name='services_offered',
            field=models.TextField(blank=True, null=True),
        ),
    ]
