# Generated by Django 4.2.13 on 2024-08-01 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treatments', '0003_treatment_approach_treatment_conditions_treated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatment',
            name='approach',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='conditions_treated',
        ),
    ]
