# Generated by Django 4.2.13 on 2024-08-01 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatments', '0004_remove_treatment_approach_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='button_text',
            field=models.CharField(default='Book Appointment', max_length=50),
        ),
    ]
