# Generated by Django 4.2.13 on 2024-08-06 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='treatment',
            field=models.CharField(choices=[('sports therapy', 'Sports Therapy'), ('orthotics', 'Orthotics'), ('health coaching', 'Health Coaching')], default='physio', max_length=50),
        ),
    ]
