# Generated by Django 4.2.13 on 2024-07-19 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointments', '0003_alter_appointment_client_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='client_email',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='client_name',
        ),
        migrations.AddField(
            model_name='appointment',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
