# Generated by Django 4.2.13 on 2024-07-02 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_remove_user_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={},
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='client',
        ),
        migrations.AddField(
            model_name='appointment',
            name='client_email',
            field=models.EmailField(default='default@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='appointment',
            name='client_name',
            field=models.CharField(default='default_name', max_length=100),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
