# Generated by Django 4.2.13 on 2024-07-20 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_remove_appointment_client_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='treatment',
            field=models.CharField(choices=[('physio', 'Physiotherapy'), ('massage', 'Massage Therapy'), ('acupuncture', 'Acupuncture')], default='physio', max_length=50),
        ),
    ]
