# Generated by Django 4.2.13 on 2024-07-18 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_testimonial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testimonial',
        ),
    ]
